# -*- coding: utf-8 -*-
"""GS_SERS_Daniel_567894.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BM_GjHxDjuqeyV28I5Z4v28d6jF-mFnb

Global Solution - PROJETO DE ANÁLISE DE DADOS DE CONSUMO ENERGÉTICO - SMART BUILDING

Aluno: Daniel Silva de Castro - RM 567894

##1. Criação de um dataset com dados simulados
"""

import pandas as pd
import numpy as np
import datetime

# Configura a simulação
np.random.seed(42)
num_dias = 30
datas = pd.date_range(start='2023-10-01', periods=num_dias * 24, freq='h')

# Cria dados simulados
dados = {
    'data_hora': datas,
    'ocupacao_pessoas': [],
    'consumo_kwh': [],
    'temperatura_externa': np.random.uniform(15, 35, len(datas)) # Temperatura entre 15 e 35 graus
}

for data in datas:
    hora = data.hour
    dia_semana = data.weekday() # 0=Segunda, 6=Domingo

    # Lógica de ocupação: alta em dias de semana (9h-18h), baixa à noite/fim de semana
    if dia_semana < 5 and 8 <= hora <= 18:
        ocupacao = np.random.randint(50, 100)
        consumo_base = 150 # Consumo alto
    else:
        ocupacao = np.random.randint(0, 5) # Noite/Fim de semana
        consumo_base = 40 # Consumo "morto" (standby, servidores, luzes esquecidas)

    # Adiciona variação aleatória e influência da temperatura
    consumo = consumo_base + (dados['temperatura_externa'][len(dados['ocupacao_pessoas'])] * 0.5) + np.random.normal(0, 5)

    dados['ocupacao_pessoas'].append(ocupacao)
    dados['consumo_kwh'].append(max(0, consumo)) # Garante que não seja negativo

# Criaa Dataframe e salvar CSV
df = pd.DataFrame(dados)
df.to_csv('dados_energia_escritorio.csv', index=False)

print("Arquivo 'dados_energia_escritorio.csv' criado com sucesso!")

"""##2. Leitura dos dados e relatório de diagnóstico"""

# Carrega o dataset
df = pd.read_csv('dados_energia_escritorio.csv')
# Converte coluna de texto para formato de data/hora
df['data_hora'] = pd.to_datetime(df['data_hora'])

TARIF_KWH = 0.65 # Preço hipotético do kWh

# Identificaa desperdício (consumo alto e ocupação baixa)
# Filtro: momentos em que há menos de 5 pessoas no escritório
filtro_vazio = df['ocupacao_pessoas'] < 5

total_kwh = df['consumo_kwh'].sum()
kwh_desperdicado = df[filtro_vazio]['consumo_kwh'].sum()
custo_desperdicado = kwh_desperdicado * TARIF_KWH

print(f"--- RELATÓRIO DE DIAGNÓSTICO ---")
print(f"Total de Horas Analisadas: {len(df)}")
print(f"Consumo Total: {total_kwh:.2f} kWh")
print(f"Consumo em momentos de Ociosidade: {kwh_desperdicado:.2f} kWh")
print(f"Representatividade do Desperdício: {(kwh_desperdicado/total_kwh)*100:.1f}% do total")
print(f"Custo Financeiro da Ineficiência: R$ {custo_desperdicado:.2f}")

"""##3. Impacto da automação predial"""

# Hipótese da solução:
# Instalação de automação predial (IoT) que reduz o consumo em 60%
# quando a ocupação é menor que 5 pessoas.
FATOR_REDUCAO = 0.60
FATOR_EMISSAO_CO2 = 0.092 # kg CO2 por kWh (média aproximada rede brasileira)

# Cálculo da economia
economia_kwh = kwh_desperdicado * FATOR_REDUCAO
economia_financeira = economia_kwh * TARIF_KWH
co2_evitado = economia_kwh * FATOR_EMISSAO_CO2

print(f"--- IMPACTO DA SOLUÇÃO PROPOSTA ---")
print(f"Ação: Automação de climatização e iluminação baseada em ocupação.")
print(f"--------------------------------------------------------------")
print(f"1. Eficiência Energética (Economia): {economia_kwh:.2f} kWh")
print(f"2. Impacto Financeiro (Redução de Custo): R$ {economia_financeira:.2f}")
print(f"3. Sustentabilidade (CO2 Evitado): {co2_evitado:.2f} kg")
print(f"--------------------------------------------------------------")

"""##4. Gráfico"""

# Selecionaa apenas um dia de exemplo para o gráfico ficar legível
dia_exemplo = df[df['data_hora'].dt.date == df['data_hora'].dt.date.iloc[0]].copy()
horas = dia_exemplo['data_hora'].dt.hour

# Onde a ocupação é baixa (<5 pessoas), reduzimos o consumo em 60%
mask_ocioso = dia_exemplo['ocupacao_pessoas'] < 5
dia_exemplo['consumo_otimizado'] = dia_exemplo['consumo_kwh']
dia_exemplo.loc[mask_ocioso, 'consumo_otimizado'] = dia_exemplo.loc[mask_ocioso, 'consumo_kwh'] * (1 - FATOR_REDUCAO)

plt.figure(figsize=(12, 6))

# Consumo atual
plt.plot(horas, dia_exemplo['consumo_kwh'],
         label='Cenário Atual (Sem automação)', color='red', alpha=0.7, linewidth=2)

# Consumo proposto
plt.plot(horas, dia_exemplo['consumo_otimizado'],
         label='Cenário Futuro (Com IoT/Smart Grid)', color='green', linestyle='--', linewidth=2)

plt.fill_between(horas, dia_exemplo['consumo_kwh'], dia_exemplo['consumo_otimizado'],
                 color='green', alpha=0.1, label='Energia Economizada')

plt.title('Comparativo de Eficiência Energética: Um Dia Típico de Trabalho', fontsize=14)
plt.xlabel('Hora do Dia', fontsize=12)
plt.ylabel('Consumo (kWh)', fontsize=12)
plt.legend()
plt.grid(True, alpha=0.3)
plt.xticks(range(0, 24)) # Mostra todas as horas no eixo X

plt.tight_layout()
plt.show()